# Generated by Django 5.1.6 on 2025-03-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('student', '0003_delete_student_profilepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='user',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admins',
        ),
        migrations.DeleteModel(
            name='Guests',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
