# Generated by Django 5.1.6 on 2025-02-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
