# Generated by Django 5.1.6 on 2025-02-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
