# Generated by Django 5.1.6 on 2025-03-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
