# Generated by Django 5.1.6 on 2025-03-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
