# Generated by Django 5.1.6 on 2025-03-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
