# Generated by Django 5.1.6 on 2025-03-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
