# Generated by Django 5.1.6 on 2025-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.CharField(choices=[('student', 'student'), ('Teacher', 'Teacher'), ('Parent', 'Parent'), ('guest', 'guest')], max_length=20),
        ),
    ]
