# Generated by Django 5.1.6 on 2025-03-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_profilepermission_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_ProfilePermission',
        ),
    ]
