# Generated by Django 5.1.6 on 2025-03-15 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profilepermission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_permissions', to='student.student'),
        ),
    ]
